### ISSUE TITLE
Nice job, 请添加我的扩展 Fairy Dict

### ISSUE THREAD

**Issue by revir** [GDG-Xian/OpenSourceChromeApps-CN#2]
chrome 上的词典扩展，学习英语的好帮手！

[github](https://github.com/revir/FairyDict)  
[chrome web store](https://chrome.google.com/webstore/detail/fairydict/gpdpcfgfmgkmljmhhnedefdaadgehaah)

Thanks!

**Comment by greatghoul** [comment]
相比 Issue, 更乐意接受 Pull Request，如果乐意的话，请给我提个 PR。

**Comment by revir** [comment]
sure, thanks
